### ISSUE TITLE
OO version

### ISSUE THREAD

**Issue by ramblerswebs** [mapcode-foundation/mapcode-php#1]
Hi
I am a member of the Ramblers (Derby & South Derbyshire Group) and I was wondering if we should promote Mapcodes for use in the countryside for meeting places in the UK. Postcodes being useless for many areas.
When I look at the PHP code I find the includes define global variables rather than the system using classes.
So two questions
Are you planning a true OO version in PHP?
Does the current code work with PHP 7?

Lastly I did run the unit test which seemed to complete ok but not knowing what output it should produce I did not know if it had worked.

**Comment by rijnb** [comment]
Hi, perhaps it's best if you contact me directly at info@mapcode.com for more extensive information (I can give you a call if you send me a phone number). 
But let me reply here as well: Yes, it seems to make sense to use mapcodes in the countryside.

Our current PHP code base was converted to PHP from our C/C++ library, but it lags a bit behind the implementation of the C/C++ and Java libraries. There have been fixes in the C/C++ library (especially on thread-safety) and the API was cleaned up. 

There are no plans to convert the PHP (or C/C++) implementation to OO version, because that doesn't make much sense for this library. But I agree the external interface must be proper and support OO. (We've worked a lot on that, specifically in the Java library.)

We plan to get the PHP library on par with the latest C/C++ library again, but we have no release date for that. 

Personally, I would strongly recommend looking at the Java library instead, which has a much cleaner interface and is extremely efficient. Alternatively, you could use the C/C++ library, which has been cleaned up quite a bit as well.

Or, maybe the easiest option would be to use the online REST API at https://api.mapcode.com/mapcode, which is very to use and to integrate with other systems. With just 2 simple rest calls you can convert back and forth between mapcodes and coordinates.

Finally, we've just released (this week) an app on the Apple AppStore which uses the REST API as well. Check it out at: https://itunes.apple.com/us/app/mapcode-official-app-from/id1141862251?mt=8

Regards and drop me a note at info@mapcode.com if you have further questions,
-Rijn
